# 1.1

## (a)

In [50]:
import torch
image_size = (10, 11)
image = torch.randn(1, 1, 10, 11).float()
# input = torch.randn()

# image = image.unsqueeze(2).unsqueeze(0)
image.shape

torch.Size([1, 1, 10, 11])

In [51]:
import torch.nn as nn

In [52]:
conv = nn.Conv2d(in_channels=1, out_channels=1,kernel_size=(5,5), stride=2)

In [53]:
conv

Conv2d(1, 1, kernel_size=(5, 5), stride=(2, 2))

In [54]:
conv(image).shape

torch.Size([1, 1, 3, 4])

## (c)

In [86]:
m = nn.Conv1d(in_channels=1, out_channels=2, kernel_size=5, stride=2)
input = torch.randn(1, 1, 7)
output = m(input)

In [87]:
input.shape

torch.Size([1, 1, 7])

In [88]:
output.shape

torch.Size([1, 2, 2])

In [80]:
m.weight.shape

torch.Size([2, 1, 5])

In [90]:
input @ m.weight

RuntimeError: Expected batch2_sizes[0] == bs && batch2_sizes[1] == contraction_size to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

# generate mask

In [1]:
import torch

In [26]:
max_len = 10
delay = torch.randint(max_len,(4,))


In [24]:
# mask = torch.zeros(4, 10)
mask

tensor([1, 2, 2, 5])

In [27]:
delay

tensor([2, 5, 5, 1])

tensor([[0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])